### ISSUE TITLE
error: node-sass version 0.8.4 is not available in the npm registry

### ISSUE THREAD

**Issue by maxlath** [lgollut/meteor-foundation5-sass#6]
hi,
I got the following error message when doing `mrt add foundation5-sass`

```
meteor-scss: updating npm dependencies -- node-sass...
=> Errors while scanning packages:

While building plugin `meteor-scss` in package `scss`:
error: node-sass version 0.8.4 is not available in the npm registry

While loading plugin `meteor-scss` from package `scss`:
module.js:338:15: Cannot find module 'node-sass'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object._.extend.Npm.require (/home/maxlath/.meteor/tools/c2a0453c51/tools/bundler.js:1107:22)
  at Package (packages/meteor-scss/plugin/compile-scss.js:2)
  at <runJavaScript-3>:59:4
  at <runJavaScript-3>:66:3
```

**Comment by maxlath** [comment]
actually, `meteor add scss` returns the same output, so I guess it's the wrong place for this report. Shall I let it here for others having the same issue?

**Comment by lgollut** [comment]
Hmm... I can't reproduce this issue. Did you try to `rm -rf packages/scss` to remove the package folder and then rerun `mrt update` ?
